name: test

on: [pull_request]

jobs:
  Linux:
    strategy:
      fail-fast: false
      matrix:
        include:
        - vimbin: nvim
          vimtag: stable
        # - vimbin: nvim
          # vimtag: v0.11.6
        # - vimbin: nvim
          # vimtag: v0.10.4
        # - vimbin: nvim
          # vimtag: v0.9.5
        # - vimbin: nvim
          # vimtag: v0.8.3
        # - vimbin: nvim
          # vimtag: v0.7.2
        - vimbin: nvim
          vimtag: v0.6.1
    runs-on: ubuntu-22.04
    env:
      VIM_BIN: ${{ matrix.vimbin }}
      VIM_TAG: ${{ matrix.vimtag }}
      DEPS: /home/runner/work/spacevim/deps
      DISABLE_ES: ${{ matrix.disable_es }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl lua5.2 liblua5.2-dev
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v4
      env:
        NEOVIM_VERSION: ${{ matrix.vimtag }}
    - name: Run test
      run: |
        if [ "$VIM_BIN" = "nvim" ]; then
          export PATH="${DEPS}/_neovim/${VIM_TAG}/bin:${PATH}"
          export VIM="${DEPS}/_neovim/${VIM_TAG}/share/nvim/runtime"
          export VIM_ES="--headless"
        else
          export PATH="${DEPS}/_vim/${VIM_TAG}/bin:${PATH}"
          export VIM="${DEPS}/_vim/${VIM_TAG}/share/vim"
          if [ "$DISABLE_ES" = "true" ]; then
            export VIM_ES=""
          else
            export VIM_ES="-Es"
          fi
        fi
        export PATH="/home/runner/.local/bin:${PATH}"
        echo "\$PATH: \"${PATH}\""
        echo "\$VIM: \"${VIM}\""
        echo "=================  ${VIM_BIN} version ======================"
        $VIM_BIN --version
        pip3 install --upgrade pip
        pip3 install covimerage virtualenv codecov
        make test-coverage
        covimerage -vv xml --omit 'build/*' --omit 'bundle/*'
        codecov -X search gcov pycov -f coverage.xml
